
const ActionTypes={
GET_CAT : 'GET_CAT',
GET_CAT_RESPONSE : 'GET_CAT_RESPONSE',
UPDATE_CAT : 'UPDATE_CAT',
CREATE_CAT : 'CREATE_CAT',
CREATE_CAT_RESPONSE : 'CREATE_CAT_RESPONSE',
UPDATE_CAT_RESPONSE : 'UPDATE_CAT_RESPONSE',
DELETE_CAT : 'DELETE_CAT',
DELETE_CAT_RESPONSE : 'DELETE_CAT_RESPONSE',

SKILL_TYPE : 'SKILL_TYPE',
SKILL_TYPE_RESPONSE : 'SKILL_TYPE_RESPONSE',
CREATE_SKILLTYPE : 'CREATE_SKILLTYPE',
CREATE_SKILLTYPE_RESPONSE : 'CREATE_SKILLTYPE_RESPONSE',
DELETE_SKILLTYPE : 'DELETE_SKILLTYPE',
DELETE_SKILLTYPE_RESPONSE : 'CREATE_SKILLTYPE_RESPONSE',
UPDATE_SKILLTYPE : 'UPDATE_SKILLTYPE',
UPDATE_SKILLTYPE_RESPONSE : 'UPDATE_SKILLTYPE_RESPONSE',

SKILL_TEMPLETE : 'SKILL_TEMPLETE',
SKILL_TEMPLETE_RESPONSE : 'SKILL_TEMPLETE_RESPONSE',


GET_MODULE : 'GET_MODULE',
GET_MODULE_RESPONSE : 'GET_MODULE_RESPONSE',

GET_ADDRESSTYPE : 'GET_ADDRESSTYPE',
GET_ADDRESSTYPE_RESPONSE : 'GET_ADDRESSTYPE_RESPONSE',

GET_ROUTE_ACTIONS : 'GET_ROUTE_ACTIONS',
GET_ROUTE_ACTIONS_RESPONSE : 'GET_ROUTE_ACTIONS_RESPONSE',

GET_COUNTRY : 'GET_COUNTRY',
GET_COUNTRY_RESPONSE : 'GET_COUNTRY_RESPONSE',

GET_PROV : 'GET_PROV',
GET_PROV_RESPONSE : 'GET_PROV_RESPONSE',

GET_CITY : 'GET_CITY',
GET_CITY_RESPONSE : 'GET_CITY_RESPONSE'
};

export default ActionTypes