
const ActionTypes={
GET_CAT : 'GET_CAT',
GET_CAT_RESPONSE : 'GET_CAT_RESPONSE',

SKILL_TYPE : 'SKILL_TYPE',
SKILL_TYPE_RESPONSE : 'SKILL_TYPE_RESPONSE',

SKILL_TEMPLETE : 'SKILL_TEMPLETE',
SKILL_TEMPLETE_RESPONSE : 'SKILL_TEMPLETE_RESPONSE',
};

export default ActionTypes